### ISSUE TITLE
Miui 14 dev error con alarma. 

### ISSUE THREAD

**Issue by Alejandrollg** [deivids84/MA-XML-14-SPANISH#1]
Este bug está presente desde miui 12.
Pensé que era error mío al tener un Mi9 con versión 12 desarrollo.
Tengo ahora un Mi 12 pro. Y el error es mayor hice un update desde Miui 13 estable a 14 dev sin wipe.
Describo el error;
Cuando programo 1 alarma.
Y llega su hora, Suena y no aparece la pantalla para silenciar.
La única manera de parar la alarma es desbloquear el móvil y presionar el botón power para bloquear.
Pero hace la función de suspender temporalmente por 10 minutos y nuevamente va el bucle la manera de pararla es reiniciar el móvil.

En miui 12 ese bug era el siguiente:
Al programar la alarma y llegar a su hora con la pantalla bloqueada funciona la parada perfecta. Pero si se usa el móvil o esta desbloqueada la pantalla en uso suena la alarma y no hay manera de pararla solo se para si se reinicia.

Ese bug no lo veo en el foro, lo reporté pero no sin éxito de solución.

Espero aporte algo esto.

Saludos cordiales.

**Comment by deivids84** [comment]
Buenas,

¿Solo te pasa con el teléfono en español?

Saludos

**Comment by Alejandrollg** [comment]
Ya encontré el fallo, son los permisos de reloj, las de notificación que al actualizar la rom se han desactivado. Por algún motivo miui 14 y 12 daba ese error, he buscado por foros y esa es la solución.
