### ISSUE TITLE
No se puede personalizar el ringtone

### ISSUE THREAD

**Issue by darkevangelion** [deivids84/MA-XML-14-SPANISH#2]
Hola, primera vez que reporto un bug, no sé si es la manera correcta de reportar.

Cuando uno trata de usar un tono personal en el dispositivo, suena el sonido de Mi remix en lugar del tono que uno selecciono, con los predeterminados no hay problema, solo es con el personalizado.

Estoy usando un Xiaomi 12, la rom que estoy usando es esta xiaomi.eu_multi_XM12_V14.0.3.0.TLCCNXM_v14-13-fastboot y fue instalación limpia.

**Comment by deivids84** [comment]
Buenas,

¿Solo te pasa con el teléfono en español?

Saludos

**Comment by darkevangelion** [comment]
Hola, disculpa la tardanza en la respuesta, cambie el dispositivo a varios idiomas y lo reinicie y trate de cambiar el ringtone y sigue haciendo lo mismo, incluso probe colocar el ringtone en otra carpeta para checar si era eso y continua el error.

También note que con esta nueva versión de miui las apps de mercadolibre y mercadopago entran en conflicto comporten usuario y contraseña como facebook y messenger, pero las primeras me obligan a iniciar sesión cada que cambio de app porque lo detecta como un nuevo dispositivo y en miui 13 no lo hacía.

**Comment by Dhollmen** [comment]
La probabilidad de que una determinada traducción influya en el comportamiento del sistema es realmente muy baja, o mejor aún: _inexistente_.

¿Has probado a establecer el tono desde la **aplicación de Temas**?

**Comment by darkevangelion** [comment]
Ya no alcancé a hacer esa prueba desde la app Temas, puse la actualización que pusieron ayer y ya se corrigió el problema, agradezco la ayuda.
