### ISSUE TITLE
Error accesibilidad miui 14.0.23.1.9 poco f3

### ISSUE THREAD

**Issue by P0taKO** [deivids84/MA-XML-14-SPANISH#3]
No funciona la accesibilidad en aplicaciones descargadas, lo activo y a los 2 minutos de vuelve a desactivar automáticamente

**Comment by deivids84** [comment]
Buenas,

¿Solo te pasa con el teléfono en español?

Saludos

**Comment by P0taKO** [comment]
Hola, buenas tardes, estoy probando en ingles con las mismas aplicaciones y
de momento no se quita, e reiniciado el movil y va bien de momento le dejo
en ingles jj
Un saludo y muy buen dia!

**Comment by P0taKO** [comment]
Tambien me pasa, que a veces (es la segunda vez que me pasa) que como que
esta activado pero no lo coje la aplicacion, de momento en esta app, tengo
como que desactivarlo y activarlo nuevamente, es doble touch la app, en las
otras que estan activadas si que lo coje sin problemas, tambien me pasa que
uso un tema modificado y tiene en el apartado de ajustes de pantalla de
bloqueo, como dos versiones, la v2 que es un estilo de bloqueo y v3 que es
otro, lo activo y no lo activa al menos que reinicie el movil, pero me
parece mas fallo de compatibilidad que de la version en si

**Comment by P0taKO** [comment]
Aun asi sigue fallando no se si sera en esas apps o algo pero no lo coje en
esta al rato se quito tambien

**Comment by Dhollmen** [comment]
La probabilidad de que una determinada **traducción** influya en el comportamiento de cualquier app ajena al sistema es realmente muy baja, o mejor: _inexistente_.

Para un correcto diagnóstico debes comenzar por **desinstalar**:

1) El tema que estás usando, seleccionar el estandard y reiniciar.
2) Si no utilizas la app de escritorio de Poco, la que estés usando.
3) Las apps que dan problemas y reiniciar otra vez.

Una vez que el sistema esté relativamente "limpio" es el momento de comprobar (_el idioma da lo mismo_) que es lo que te produce el problema.

Debes comenzar por instalar (una cada vez) las apps y _probar como va con cada una, antes de instalar la siguiente_,
Sin prisas y esperando tiempo suficiente para asegurarte de que no falla.

Si ninguna falla, ya sabes más.

**Comment by P0taKO** [comment]
Pues si que parece que es del tema lo que da conflicto, lo e dejado todo
como indicas reiniciando y demas y ahora no se quitan, te comento si
encuentro algo
Un saludo!
