### ISSUE TITLE
Translation error in the gallery and settings.

### ISSUE THREAD

**Issue by Juanpablobq** [deivids84/MA-XML-14-SPANISH#4]
When the ROM is set in Spanish, the gallery has a little translation problem, he explained to me, the date is shown above a photo, but that date is still in English and I considered that as an error. The other problem is in settings > screen > color scheme, the word lived is not translated in Spanish, it is still in English, those are the errors that I have found. I wish they would be fixed, thanks.

**Comment by Dhollmen** [comment]
**Tema 1: el mes en la Galería.**
Lo estamos revisando a ver de lo que se trata.

**Tema 2: 'lived' en color en Ajustes.**
Asumo que te refieres a '_Vivid_'.  En mi opinión, puede  permanecer sin traducir, pero no obstante lo he cambiado para versiones posteriores.
Entre '_vívido_' e '_intenso_' me he decantado por '_intenso_'

**Comment by Dhollmen** [comment]
**Tema 1: el mes en la Galería.**
Revisado y solucionado.
Gracias por tu colaboración.
