### ISSUE TITLE
Galery dont save any modification

### ISSUE THREAD

**Issue by Teto78Spain** [deivids84/MA-XML-14-SPANISH#5]
When edit a photo, galery ask you where you want save It, but never make It. Its imposible save a photo or pic modified.

**Comment by Dhollmen** [comment]
No indicas que rom, que versión de MIUI y que dispositivo tienes.
Tal vez podría tratarse de un problema de permisos

Por ejemplo en mi caso, con un Mi 10T lite y Miui 13, no ocurre. 

De cualquier manera, se trata de algo totalmente ajeno a la traducción al Español.
