### ISSUE TITLE
Ninguna app para analizar WiFi funciona en miui 14 android 13 - Xiaomi 12

### ISSUE THREAD

**Issue by darkevangelion** [deivids84/MA-XML-14-SPANISH#6]
Hola, al parecer encontré un nuevo bug en el sistema con Xiaomi 12 desde enero, pero no estaba seguro hasta que cambié a rom oficial para testear

Usaba esta rom de xiaomi.eu antes del cambio...

xiaomi.eu_multi_XM12_V14.0.6.0.TLCCNXM_v14-13 <--not root

Desde la actualización del 24 de diciembre 2022 a Miui 14 con android 13 todas las apps que analizan las señales de wifi para checar canales, intensidad y versión, no están funcionando, suelo utilizar esta...

https://play.google.com/store/apps/details?id=com.vrem.wifianalyzer

Sin embargo, probando otras tienen el mismo problema solo se queda cargando y no muestra nada, antes de actualizar a la versión de Miui 14 con android 13 del 24 de diciembre para xiaomi 12, estaba usando esta rom...

xiaomi.eu_multi_XM12_V13.0.41.0.SLCCNXM_v13-12 <--not root

y funcionaba sin problemas incluso con las actualizaciones pasadas.

Haciendo pruebas con un amigo que tiene el Xiaomi 12 pro con la versión de Miui 14 con android 13 Xiaomi EU rom V14.0.23.2.13.DEV <--not root si funciona la app, y en mi xiaomi 12 probando la rom oficial global V14.0.2.0.TLCMIXM <--not root también funciona.

Ya intenté cambiar varias configuraciones y sigue sin funcionar, como las uso para mi trabajo es un poco molesto no poder utilizar esas apps.

**Comment by Dhollmen** [comment]
No sería extraño que se tratara de un asunto de permisos, aunque es posible que la Rom tenga algún "cable suelto" ;)

De todas maneras, este es un asunto que debes tratar en el foro de xiaomi.eu.

Ten en cuenta que en este repositorio solo nos ocupamos de las traducciones de la rom, en este caso al español.
Estaremos encantados de corregir cualquier anomalía de traducción que detectes, pero poca ayuda te podemos prestar para resolver bugs del sistema.

Saludos cordiales

**Comment by darkevangelion** [comment]
oh ya, pensé que era para bugs del sistema en español, lo siento, voy a revisar en el foro, gracias y disculpa.
