### ISSUE TITLE
  -

### ISSUE THREAD

**Issue by antonybonii** [deivids84/MA-XML-14-SPANISH#7]

**Comment by Dhollmen** [comment]
Sentimos no poder ayudarte ya que no está a nuestro alcance solucionar tu problema.

Debes reportarlo en el foro correspondiente de **xiaomi.eu**.

Este repositorio es exclusivamente para las traducciones de la Rom y tan solo nos podemos ocupar de los posibles errores que encuentres en las mismas.

Un saludo cordial.
