### ISSUE TITLE
Error image on the screen of hidden applications

### ISSUE THREAD

**Issue by Dieck97** [deivids84/MA-XML-14-SPANISH#8]
When making the gesture to access hidden applications, on the screen where the password is entered, the image of the padlock is displayed incorrectly.

**Comment by Dhollmen** [comment]
I can't reproduce this on my device.
You don't state your device model and MiUI's version installed.

On the other hand, this is a exclusively repository  for the MiUI's translation to Spanish language.
I guess your problem is not related to the translation's quality .
